[package]
name = "iot_final_virtdriver"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.1"
evdev = "0.12.0"
lazy_static = "1.5.0"
nalgebra = "0.33.2"
uinput = "0.1.3"
x11 = "2.21.0"
xi = "0.1.1"
